@startuml
'http://plantuml.com/dot
digraph foo {
  CustomerCustomerDemo -> CustomerDemographics;
  CustomerCustomerDemo -> Customers;
  Employees -> Employees;
  EmployeeTerritories -> Employees;
  EmployeeTerritories -> Territories;
  Order Details -> Orders;
  Order Details -> Products;
  Orders -> Customers;
  Orders -> Employees;
  Orders -> Shippers;
  Products -> Categories;
  Products -> Suppliers;
  Territories -> Region;
}

@enduml